on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: "CI Pipeline"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    env:
      VERSION: v0.9.0
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          wget -q https://github.com/koalaman/shellcheck/releases/download/$VERSION/shellcheck-$VERSION.linux.x86_64.tar.xz \
            -O shellcheck.tar.xz
          tar -xf shellcheck.tar.xz
          mv shellcheck-$VERSION/shellcheck .
          rm -rf shellcheck.tar.xz shellcheck-$VERSION

      - name: Run Shellcheck on completion scripts
        run: |
          ./shellcheck --version
          ./shellcheck -e SC2148 completions/bash/gw completions/zsh/gw completions/fish/gw

  perl-tests:
    name: Perl Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version: ['5.20']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install Perl dependencies
        run: |
          cpanm --notest Test::More File::Temp File::Path File::Copy

      - name: Make scripts executable
        run: |
          chmod +x bin/gw bin/test

      - name: Run tests
        run: |
          ./bin/test --verbose
